### ISSUE TITLE
LIST benchmarks can be inaccurate with initial count

### ISSUE THREAD

**Issue by roycaihw** [jpbetz/conversion-webhook-example#4]
The LIST benchmarks are using "ResourceVersion=0" in their initial counting. The watch cache count may be lagging behind the actual object count in etcd, causing the benchmark to create more than needed objects

I've seen LIST benchmark creates more than 10000 CRs

to fix: don't specify resource version in list option

**Comment by jpbetz** [comment]
Yes, let's fix this. It's a problem.

We should probibly also create each long lived dataset in a separate namespace, e.g. one namespace for 100foos, 1000foos, ...

**Comment by roycaihw** [comment]
fixed by https://github.com/jpbetz/conversion-webhook-example/pull/3/commits/76f5aec6c254925ace1066ca672e89524c732523

> We should probibly also create each long lived dataset in a separate namespace, e.g. one namespace for 100foos, 1000foos, ...

good point. I'll keep that in mind when I do the refactoring
