### ISSUE TITLE
Object creation might fail due to conflict name

### ISSUE THREAD

**Issue by roycaihw** [jpbetz/conversion-webhook-example#5]
I didn't verify this.

In our benchmarks, we assume that we create unique CR/Endpoints objects by having timestamp in object names
```
metadata:
  name: barv1-{timestamp in nanosecond}
```
This might be a problem when we bring up goroutines to do massive creation in parallel (e.g. in LIST benchmarks). I could imagine two goroutines sending requests at the same time and one request fails due to name conflict

(the problem could be rare or not existing, given goroutines are created in serial / some underlying assumption with rest client)

to fix/mitigate: add additional bit in object name unique to each goroutine, like another count

**Comment by roycaihw** [comment]
... and we didn't check error on object creation, so they could be failing silently

**Comment by jpbetz** [comment]
We should probably switch to something like https://github.com/google/uuid

**Comment by roycaihw** [comment]
fixed in 0e390bc5d3d98e365d58e928e5dc1f4fc272ef5f
